### ISSUE TITLE
Importing of ONTO keystore fails

### ISSUE THREAD

**Issue by panther142** [ontio/OWallet#102]
Users are unable to .import their ONTO keystore in OWallet due to minor differences in the keystore fornat.

**Comment by MickWang** [comment]
I just try to import with the ONTID keystore of new version ONTO and succeed. The import method of OWallet does not take the new fields as parameters. So the differences in keystore does not affect the import. Can you give us more info about the import failure?Thanks.

**Comment by panther142** [comment]
Resolved in later versions
