### ISSUE TITLE
Add support for OEP-8

### ISSUE THREAD

**Issue by hyviquel** [ontio/OWallet#125]
For now, OWallet is not able to see (and transfer) the OEP-8 token (like the pumpkins) available in the current wallet.

**Comment by GLS9000** [comment]
I have an OEP-8 token in my OWallet (ledger).It's now viewable in the wallet itself, but on the blockexplorer it is present in my OWallet address. But it would be nice to see it directly in the wallet off course.

**Comment by MickWang** [comment]
No such plan for now. Maybe add the support in the future. So please do not transfer the oep-8 tokens to your ledger wallet till we have the support on OWallet. Thanks.
