### ISSUE TITLE
Label releases with operating system type

### ISSUE THREAD

**Issue by panther142** [ontio/OWallet#129]
Rename releases to include which operating system they are for. E.g.

OWallet-0.9.3-Windows-Setup.exe
OWallet-0.9.3-Mac-Setup.dmg
OWallet-0.9.3-Linux-Setup.AppImage

Many users get confused about which file to download.

**Comment by panther142** [comment]
This was fixed for one version now it is the back to not showing which OS.

**Comment by MickWang** [comment]
will keep the correct name in later releases. Thanks
