### ISSUE TITLE
“My Stake” arrows navigate to wrong node

### ISSUE THREAD

**Issue by cuppontology** [ontio/OWallet#136]
When looking in the “My Stake” list of nodes, when clicking the arrow in the rightmost column to go to that node’s page you are always taken to the first node alphabetically, not the one selected.

**Comment by cuppontology** [comment]
I’m using the Mac version, most recent.

**Comment by MickWang** [comment]
We will fix it and release it next week.

**Comment by MickWang** [comment]
Close it after fixed.
