### ISSUE TITLE
Import NEO to Ledger

### ISSUE THREAD

**Issue by Sausalitoj** [ontio/OWallet#137]
How to import NEON wallet 2.0  into Ledger Nano S
I can open my existing NEON wallet 2.0 using my passphrase or private keys. When I open using my ledger nano s it said I have to import my wallet using new ledger public keys. I put all the required information in but nothing showed up in the new ledger wallet.  Can you please give me step by step instructions?
Thank you,

**Comment by WyattMufson** [comment]
@Sausalitoj wrong project

@MickWang this should be closed
