### ISSUE TITLE
Ledger Wallet in OWallet freezes

### ISSUE THREAD

**Issue by feliasson** [ontio/OWallet#138]
Windows 10 - OWallet 0.9.4 freezes while opening Ledger-wallet. 
- Sometimes does not seem to recognize ONT-app has been opened on Ledger
- Sometimes opens Wallet after X minutes waiting
- Meanwhile OWallet client is completly frozen and nothing can be pressed
- While Ledger-wallet finally opened, any action might freeze it, "Redeem" or "Stake authorization" etc. 
- It does seem to be working from time to time, but there are no loading screens or work progress available so it is hard to tell.

**Comment by MickWang** [comment]
Please upgrade OWallet to latest version  and see will it still happen.
