### ISSUE TITLE
Invalid ONT ID - just created on latest version

### ISSUE THREAD

**Issue by Crypto-Therapist** [ontio/OWallet#141]
I just updated to the latest version of OWallet, created an ONT ID and I get the error message - invalid ONT ID - when I try to login to Node Management. Please advise.

**Comment by MickWang** [comment]
The Node Management is only for the candidate node users. If you are normal user and want to participate in stake authorization, please select the Stake Authorization option.

**Comment by Crypto-Therapist** [comment]
Thank you, Mick Wang,

I have gained access to the stake authorization and reclaimed unbound ONG -
just wanted to check on it as I had a problem with the wallet before. It
was a stupid mistake trying to enter the wrong area.

I appreciate your response. It is difficult for ordinary people to manage
everything crypto without a user manual!

Gratefully,
Jan Resnick in Perth
