### ISSUE TITLE
Fetch transaction failed

### ISSUE THREAD

**Issue by young-tribe** [ontio/OWallet#145]
i All,

I've updated to OWallet 0.9.6 and imported my wallet, but am receiving timeout issues, as a network error. I've attempted this via home and mobile hotspot/networks, but same outcome.

My trace is below - thanks for any time spent considering:

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> tracert explorer.ont.io

Tracing route to explorer.ont.io [104.215.199.197]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  192.168.0.1
  2    23 ms    22 ms    21 ms  205.4.96.58.static.exetel.com.au [58.96.4.205]
  3    22 ms    21 ms    21 ms  10.1.82.66
  4    44 ms    44 ms    43 ms  10.1.82.17
  5    46 ms    45 ms    46 ms  ae64-0.syd-96cbe-1a.ntwk.msn.net [104.44.13.148]
  6    44 ms    46 ms    51 ms  ae22-0.icr01.syd03.ntwk.msn.net [104.44.236.46]
  7   145 ms   146 ms   147 ms  be-101-0.ibr01.syd23.ntwk.msn.net [104.44.11.101]
  8   146 ms   149 ms   145 ms  be-5-0.ibr01.mel20.ntwk.msn.net [104.44.4.231]
  9    59 ms    57 ms    56 ms  ae103-0.icr02.mel01.ntwk.msn.net [104.44.11.160]
 10   102 ms   101 ms   104 ms  ae22-0.per01-96cbe-1a.ntwk.msn.net [204.152.141.70]
 11   150 ms   147 ms   147 ms  ae26-0.icr02.sg3.ntwk.msn.net [104.44.239.227]
 12   148 ms   147 ms   151 ms  be-122-0.ibr02.sg3.ntwk.msn.net [104.44.20.19]
 13   146 ms   146 ms   145 ms  ae121-0.icr01.sg2.ntwk.msn.net [104.44.20.20]
 14     *        *        *     Request timed out.
 15     *        *        *     Request timed out.
 16     *        *        *     Request timed out.
 17     *        *        *     Request timed out.
 18     *        *        *     Request timed out.
 19     *        *        *     Request timed out.
 20     *        *        *     Request timed out.
 21     *        *        *     Request timed out.
 22     *        *        *     Request timed out.
 23     *        *        *     Request timed out.
 24     *        *        *     Request timed out.
 25     *        *        *     Request timed out.
 26     *        *        *     Request timed out.
 27     *        *        *     Request timed out.
 28     *        *        *     Request timed out.
 29     *        *        *     Request timed out.
 30     *        *        *     Request timed out.

Trace complete.

**Comment by MickWang** [comment]
The backend server of our explorer was serving lots of requests and may be not stable sometimes. We are improving it. Please change your network and try later.
Thanks.
