### ISSUE TITLE
Unbound ONG balance unstable in v0.9.6

### ISSUE THREAD

**Issue by Arnold2020** [ontio/OWallet#146]
OWallet was working well for over a month. Now, for past day, the Unbound ONG balance keeps changing and sticking at the wrong number. As example, I have approx 3 showing in wallet which is correct based on previous balances. Then sometimes it jumps to 0.15, then jumps to 0.65, then back to 3. It sticks at a wrong number for 10 seconds, or 10 minutes, or 30 minutes. I closed and reopened wallet many times, but no difference.

**Comment by Arnold2020** [comment]
[OWallet Unbound ONG not stable.docx](https://github.com/ontio/OWallet/files/2954818/OWallet.Unbound.ONG.not.stable.docx)

**Comment by Arnold2020** [comment]
[OWallet Unbound ONG not stable.docx](https://github.com/ontio/OWallet/files/2954912/OWallet.Unbound.ONG.not.stable.docx)

**Comment by Arnold2020** [comment]
The balance seem much more stable now, but:
1) I have lost approx 4 Unbound ONG
2) Will this keep happening?
Note, never any problem with balance of ONT, ONG, Claimable ONG. It is only the Unbound ONG balance which has issues. Anyone else seen this instability before?

**Comment by MickWang** [comment]
Hello, dont' worry. Your assets are not lost. The instability is due to the load balance of our explorer backend server. We are fixing it now.

**Comment by Arnold2020** [comment]
Thanks Mick. Keep up the great work.Best Regards,Paul

    On Wednesday, March 13, 2019, 10:48:07 PM EDT, MickWang <notifications@github.com> wrote:  
 
 
Hello, dont' worry. Your assets are not lost. The instability is due to the load balance of our explorer backend server. We are fixing it now.

**Comment by Arnold2020** [comment]
Thanks Mick, keep up the great work. Best Regards.

    On Wednesday, March 13, 2019, 10:48:07 PM EDT, MickWang <notifications@github.com> wrote:  
 
 
Hello, dont' worry. Your assets are not lost. The instability is due to the load balance of our explorer backend server. We are fixing it now.

**Comment by alpatel63** [comment]
I am experiencing the same issue with the Unbound ONG figures are not being updated since last 2 months or so.  What should I do to have this figure refreshed or recalculated correctly please?  Thanks in advance.  Anil
