### ISSUE TITLE
Transaction is not sent

### ISSUE THREAD

**Issue by KMFDM29** [ontio/OWallet#152]
Already 2 weeks watch This.How is it possible to send funds? How long do I have to wait for ONG or something?
![Скриншот 21-03-2019 214801](https://user-images.githubusercontent.com/41021204/54751461-c63f0d80-4c26-11e9-84d5-0dad8df63510.jpg)

**Comment by MickWang** [comment]
You need to get at least 0.01 ONG to to send any transaction., such as claim your claimable ong or transfer ONT.
