### ISSUE TITLE
BIG PROBLEMS !!! with OWallet when you send money from NEO wallet. 

### ISSUE THREAD

**Issue by aretas777** [ontio/OWallet#154]
I did send 96 ontology from my Desktop Neo wallet(MAC version) to my new Owalet(desktop mac version) today in morning. 
Neotracker.io transaction Hash bellow
6ee8c10e00525145d67a462568aeaa533b7c13ddb67825e5d80d80135c01a770

on noetraker.io this transaction showing that my Owalet adrress have balance 96.7.
When I login to my desktop Owalet balance ontology is 0.00
I created Owalet with Ledeger Nano S
If this problem will not fix planing big Youtube videos reviews!!!!

Looks like scam. Im marketer. Planing to upload many youtube with bad review on Owalet and Ontology.

**Comment by MickWang** [comment]
Dont' worry, your assets are not lost. OWallet now does not support NEP-5 tokens now and you did send the NEP-5 ONT token to the address: APQp7qrTJDbCTFb8QJRKenRj65jTzQoKXk. Please confirm this is your address and your tokens stay there safely. You can connect your ledger to other wallet that supports NEP-5 tokens, like O3 wallet , NEON wallet. Thanks.

**Comment by aretas777** [comment]
Yes this is my  adrress: APQp7qrTJDbCTFb8QJRKenRj65jTzQoKXk.
How I can safe transfer back NEON Wallet?

**Comment by aretas777** [comment]
Thank you I downloaded O3 walet....and restore my ontology

**Comment by aretas777** [comment]
Good Job Mick Wang

**Comment by MickWang** [comment]
Thanks.
