### ISSUE TITLE
Incorrect Password

### ISSUE THREAD

**Issue by Kugahara1** [ontio/OWallet#155]
Error shows up for the password entered.  How can I correct it? 
Thanks, Takao

**Comment by MickWang** [comment]
Please check if the password you entered is correct.
If you have the WIF of the wallet. You can import it again and set a new password.

**Comment by Kugahara1** [comment]
What is WI-FI, and how can I obtain it?

Takao/鈴木 孝雄
Sent by iPhone

On May 4, 2019, at 7:15 PM, MickWang <notifications@github.com> wrote:

Please check if the password you entered is correct.
If you have the WIF of the wallet. You can import it again and set a new password.

**Comment by Kugahara1** [comment]
Mick,

 

Kindly let me know what the WIF of the wallet is, and how can I obtain it?  I have problem in redeeming the claimable due to inability to log in.  Message says, 

“password error”  I need your help to reset my password.

 

Thanks,

 

Takao

Takao Suzuki

Wallet ID: Kugahara1

**Comment by MickWang** [comment]
How do you get the wallet? By creating or importing with private key? If you created it in OWallet, it must told you to backup the private key or the WIF of the wallet.(WIF is actually the same as private key). If your wallet is import into OWallet ,you must have the original private key. So you can re-import you wallet with you private key do the claim again.
