### ISSUE TITLE
Warning! missing ONT! Empty wallet

### ISSUE THREAD

**Issue by trognaz** [ontio/OWallet#158]
I believe this project is a brilliant work to defraud money.

I have deposited a total of 406 ONTs  through 3 transactions

today when I open the wallet correctly imported the .dat file and tried on 3 platforms (windows mac and linux) my wallet is completely empty !!! network error.

I want my damn money back. or I will use many more to do the advertising it deserves.

I had in mind to invest a lot in this crypt and to deposit a lot, but I was wrong. I will invest in safe and non-fraudulent projects.

Fetch transaction history failed. network error.

if you can't guarantee the safety of other people's money I hope you are a scammer and sooner or later someone will find you, but if you are not, you are a shit

And if the network will work for access to my money i have to search for buy ONG! fuck! i have to search an external service for trade and exchange ONG, lost money anymore with exchange! and send ONG to my Owallet! and hope after that work fine, and  maybe can send out this fuking ONT!!!! fuck fuck fuck! this is totally shit.

**Comment by MickWang** [comment]
Dont' worry, You asset is not lost. The network error is due to the server pressure of our explorer. Please wait for a little longer and the balance will show out. We are fixing the network error now and it will be ok soon. Thanks.

**Comment by WyattMufson** [comment]
@MickWang this should be closed

**Comment by WyattMufson** [comment]
@trognaz can you send your wallet address?
