### ISSUE TITLE
missing wallet

### ISSUE THREAD

**Issue by kbintent** [ontio/OWallet#162]
1. Transfered ONT onto newly created OWallet today using Ledger feature. 
2. Now that i return to OWallet, no ONT is visible. No Wallet. No Ont.
3. I've stored the db file, wallet address and public key
4. MacBook Pro, MacOS version 10.14.5

How do i proceed? Searching i didn't find direction on how to return to the original wallet.

**Comment by MickWang** [comment]
Please open the "Setting " page, and set the keystore file path to where you saved the keystore.db file. You will see your wallets there.

**Comment by kbintent** [comment]
worked like magic. Thanks for your help. 

    On Thursday, May 30, 2019 12:15 AM, MickWang <notifications@github.com> wrote:
 

 Please open the "Setting " page, and set the keystore file path to where you saved the keystore.db file. You will see your wallets there.—

**Comment by MickWang** [comment]
you are welcome. Closing this issue now.
