### ISSUE TITLE
incorrect upgrade version message

### ISSUE THREAD

**Issue by dakeshi** [ontio/OWallet#195]
## description
I have upgraded latest version(0.9.14) but it has upgrade notification message in the intro screen. If I click the link, it brings me this 0.9.13 version page(https://github.com/ontio/OWallet/releases/tag/v0.9.13)

<img width="1079" alt="OWallet" src="https://user-images.githubusercontent.com/8563047/63594170-b1f5a700-c5f0-11e9-8e13-712f568bb29d.png">

## test env
- Mac OS
- OWallet version: 0.9.14

**Comment by MickWang** [comment]
There is a display issue on v0.9.14 and we will release the v0.9.15 to fix it.
