### ISSUE TITLE
Showing menu text with dual language

### ISSUE THREAD

**Issue by dakeshi** [ontio/OWallet#196]
## description
It displays its menu description with dual language(english and chinese)

## expected result
showing menu text with selected language only

## screenshot
<img width="869" alt="dual_languge" src="https://user-images.githubusercontent.com/8563047/63594974-dbafcd80-c5f2-11e9-9deb-4e2d02333569.png">

## test env
- OS: Mac OS
- OWallet version: 0.9.14

**Comment by MickWang** [comment]
The dual language is designed so for now. We may update it in later version.
