### ISSUE TITLE
issue upon upgrading wallet

### ISSUE THREAD

**Issue by MairzaQouneh** [ontio/OWallet#201]
Dear Sir/ Madam,
When I upgraded my O Wallet to the latest version (9.17), this is what happened to me:
1. I was NOT able to see my coins in the wallet.
2. I imported my wallet again using my private keys, I saw the wallet, but when I clicked on the (node staking )keys to follow up on my ont staking, It kept giving this message (Network error, please try later).

Have I lost my ont?
What am I supposed to do to fix this????

**Comment by MickWang** [comment]
Hello, don't worry. Your coins are still in you wallet as you have the private keys.
Please try to switch to another node address in the setting page. Or try with other network.

**Comment by MairzaQouneh** [comment]
Thank you

Can you please elaborate, as I have limited computer capabilities?

Please bare with me

**Comment by MickWang** [comment]
That's ok.
About switching node address, Please select the "Settings" icon on the left side of OWallet, Then you will enter the setting page. You will see the "Node address" option and select other node , for example, choose http://dappnode2.ont.io.(The network must be MainNet). Then go to the staking page and see if it works. If not, you can go back to the "Settings" page to choose another node address and try again.

**Comment by MairzaQouneh** [comment]
Hi 

Looks like I messed up.

I need to start restoring my wallet and I don't know ho.
Can you please me??

**Comment by MickWang** [comment]
You can restore with your keystore file. Go to the "Setting" page, set the "Save the keystore file" path to the directory where you put the keystore.db file.

**Comment by MickWang** [comment]
Hi, have you resolve your issue?  Will close this issue now. Please feel free to reopen. Thanks.
Restoring keystore file is as below shows.
![image](https://user-images.githubusercontent.com/6647774/87913408-aaa97880-caa1-11ea-858b-ce98a989d08a.png)
