### ISSUE TITLE
Countdown round not working

### ISSUE THREAD

**Issue by jonatanblockchain** [ontio/OWallet#220]
![image](https://user-images.githubusercontent.com/29895459/73609546-10c34180-45cf-11ea-8702-20336d45bc45.png)

Version: 0.92 / Windows X64

**Comment by Hummiesme** [comment]
Does it have match on android smartphone or only on computer.? Owallet this unfair. Dont have android version

**Comment by MickWang** [comment]
Please upgrade to the latest version. It is fixed. Thanks.
