### ISSUE TITLE
OWallet Empty fetch transaction failed

### ISSUE THREAD

**Issue by Fawzang** [ontio/OWallet#222]
Hi,
My wallet is saying FETCH TRANSACTION HISTORY DAILED NETWORK ERROR.

HELP !!!

**Comment by Fawzang** [comment]
My wallet is Empty..how do I fix this !!!

**Comment by bjindal01** [comment]
I have the same problem!! Any ideas, all my ONT and ONG earned are lost. Now I get an error about Keystore file not being valid or available when I do see it.

**Comment by bjindal01** [comment]
Upgrading to latest ONT wallet fixed this! Had to import the .dat file with new version and it all seems to work.

**Comment by Hummiesme** [comment]
Did you download that in playstore owallet didnt match on my phone version.! I am pie 9.0 helio p22 what about in the web does it have site? I cannot evn find it pls help I am just a newbie. Thanks.

**Comment by Okhen** [comment]
Pls I can’t see any balance on my wallet 
It says fetch balance failed.Network error pls try later

**Comment by MickWang** [comment]
Please upgrade to the latest version. Thanks
