### ISSUE TITLE
Owallet upgrade to 0.9.3 Error

### ISSUE THREAD

**Issue by Zeetster2K** [ontio/OWallet#225]
I upgraded my owallet to version 0.9.3 and all my ont and ong are lost. I have read previous issues and comments where it is suggested to import the keystore file or .dat file. Can someone please guide me step by step how to do this.

**Comment by Hummiesme** [comment]
Did you download that in playstore owallet didnt match on my phone version.! I am pie 9.0 helio p22 what about you does it have site? I cannot evn find it pls help I am just a newbie. Thanks.

**Comment by MickWang** [comment]
> I upgraded my owallet to version 0.9.3 and all my ont and ong are lost. I have read previous issues and comments where it is suggested to import the keystore file or .dat file. Can someone please guide me step by step how to do this.

Hi，Please show more details of your issus. And  importing the keystore file or .dat file is easy. You can follow these screenshots.
1. Load your keystore.db file.
![image](https://user-images.githubusercontent.com/6647774/87912874-b183bb80-caa0-11ea-9581-36c4abfbe8ab.png)
 
2.  Import your .dat file. Please set the keystore.db file path before importing
![image](https://user-images.githubusercontent.com/6647774/87913050-07586380-caa1-11ea-95a9-f74557cbe08d.png)
![image](https://user-images.githubusercontent.com/6647774/87913087-16d7ac80-caa1-11ea-82b7-e7846f55f959.png)

**Comment by MickWang** [comment]
> Does it have match on android smartphone or only on computer.? Owallet this unfair. Dont have android version

You can try ONTO.https://onto.app/
