### ISSUE TITLE
UNCLAIMED ONG shows in O3 Wallet/Staketology but not in OWallet

### ISSUE THREAD

**Issue by kkekoa** [ontio/OWallet#259]
See the two attached prinscreens.  The UNCLAIMED ONG shown on the Staketology printscreen doesn't show on the OWallet printscreen.  Why it is missing or is it there and I'm not finding it?
![OWallet stake authorization screen 201127](https://user-images.githubusercontent.com/36653768/100485292-97d42f80-30a3-11eb-9ba2-6cdfb1918496.png)
![O3-staketology staked info 201127](https://user-images.githubusercontent.com/36653768/100485306-9efb3d80-30a3-11eb-8e3f-fdac3869677c.png)

**Comment by sulingxiao** [comment]
Hello, the Ontology mainnet will no longer distribute ong to the address holding ont after the update of 20200707 (referring to the part that needs to be claimed before), and other wallets have not made corresponding updates.
In fact, if you see this amount in other wallets and do a claim operation, you will not get ong.

**Comment by sulingxiao** [comment]
> See the two attached prinscreens. The UNCLAIMED ONG shown on the Staketology printscreen doesn't show on the OWallet printscreen. Why it is missing or is it there and I'm not finding it?
> ![OWallet stake authorization screen 201127](https://user-images.githubusercontent.com/36653768/100485292-97d42f80-30a3-11eb-9ba2-6cdfb1918496.png)
> ![O3-staketology staked info 201127](https://user-images.githubusercontent.com/36653768/100485306-9efb3d80-30a3-11eb-8e3f-fdac3869677c.png)

Hello, the Ontology mainnet will no longer distribute ong to the address holding ont after the update of 20200707 (referring to the part that needs to be claimed before), and other wallets have not made corresponding updates.
In fact, if you see this amount in other wallets and do a claim operation, you will not get ong.
