### ISSUE TITLE
Owallet is not generating ONG. 

### ISSUE THREAD

**Issue by ACX11** [ontio/OWallet#268]
Hey,

I have been holding ONT in Owallet for a year or more and ONG is still 0. Because of no ONG, I can't withdraw my ONT tokens to exchange. I can't also stake them to get more ONG because if I want to stake them I have to have some ONG... 

How can I get access to my ONT? 

Thanks.

**Comment by Dumontiskooo** [comment]
> I also have ONT in my owallet and want to transfer some to the exchange to take partial profits but have the same problem re: no ONG. This is crazy, I don't want to stake my ONT, I want to trade it and I need to control this, not owallet. I would have never bought ONT if I'd known I'd be stuck with no trading options. This is not right, I'm so frustrated I'd like to just get rid of all ONT and move on to more reasonable coins. Appreciate any suggestions to get out of this situation. Thanks.

Is there any problem to go to - https://coinmarketcap.com/currencies/ontology-gas/markets/ to check all markets where ONG is traded and buy it here? Most popular is probably Binance. All you need is 0.05 ONG per transaction. So buy the amount you need and withdraw it to your wallet where you have ONT, no rocket science, you could do it maybe faster than you write that comment.... If you really cannot buy it on exchange, or do not have that 1$ to spend, drop here your wallet address and I can donate you ...

**Comment by sidsamest** [comment]
Hello,

Thanks for your quick response, very much appreciated. I’m in the USA and, while all of the exchanges available to those located in the US have ONT available, the only option for me to acquire ONG is on gate.io with USDT. I can’t deposit US$ on gate.io, so must purchase USDT on BinanceUS, then deposit to gate.io. The problem with that is that the only common network between BinanceUS and gate.io is ETH, and the gas fee for the transfer is US$16 in order for me to purchase enough ONG for 2 withdrawals (I want to sell 1/2 my ONT now and hold the rest for a longer term but be able to withdraw it on short notice). If you are willing to deposit the ONG for 2 withdrawals into my wallet, I’m more than happy to reimburse you if you let me know how. Also, I’m not sure if my response will be seen publicly so a little apprehensive about sending my wallet address in this format. Please let me know if there is a more secure way. I appreciate any way that we can work this out.

Thanks, 
Sam Sidney

**Comment by Dumontiskooo** [comment]
> Hello, Thanks for your quick response, very much appreciated. I’m in the USA and, while all of the exchanges available to those located in the US have ONT available, the only option for me to acquire ONG is on gate.io with USDT. I can’t deposit US$ on gate.io, so must purchase USDT on BinanceUS, then deposit to gate.io. The problem with that is that the only common network between BinanceUS and gate.io is ETH, and the gas fee for the transfer is US$16 in order for me to purchase enough ONG for 2 withdrawals (I want to sell 1/2 my ONT now and hold the rest for a longer term but be able to withdraw it on short notice). If you are willing to deposit the ONG for 2 withdrawals into my wallet, I’m more than happy to reimburse you if you let me know how. Also, I’m not sure if my response will be seen publicly so a little apprehensive about sending my wallet address in this format. Please let me know if there is a more secure way. I appreciate any way that we can work this out. Thanks, Sam Sidney
> […](#)
> On Apr 9, 2021, at 4:04 AM, Dumontiskooo ***@***.***> wrote: ﻿ I also have ONT in my owallet and want to transfer some to the exchange to take partial profits but have the same problem re: no ONG. This is crazy, I don't want to stake my ONT, I want to trade it and I need to control this, not owallet. I would have never bought ONT if I'd known I'd be stuck with no trading options. This is not right, I'm so frustrated I'd like to just get rid of all ONT and move on to more reasonable coins. Appreciate any suggestions to get out of this situation. Thanks. Is there any problem to go to - https://coinmarketcap.com/currencies/ontology-gas/markets/ to check all markets where ONG is traded and buy it here? Most popular is probably Binance. All you need is 0.05 ONG per transaction. So buy the amount you need and withdraw it to your wallet where you have ONT, no rocket science, you could do it maybe faster than you write that comment.... If you really cannot buy it on exchange, or do not have that 1$ to spend, drop here your wallet address and I can donate you ... — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Send me dm on telegram:
https://t.me/dumontiskooo
