### ISSUE TITLE
Owallet mac ,network error ,stop showing balance 

### ISSUE THREAD

**Issue by Volodymyr2929** [ontio/OWallet#56]
Desk top  Owallet stop showing funds.Look like visual issue.network error appear all the time.How long will it take to fix...Thanks

**Comment by Volodymyr2929** [comment]
How long will it take to fix...Thanks

**Comment by MickWang** [comment]
We will fix the network errors ASAP.Before that, please switch your network service and try again. Thanks

**Comment by Volodymyr2929** [comment]
What do you mean about switching network service and where can i find export IP. Easy for you but not clear for me . thanks .

**Comment by MickWang** [comment]
You can google it as keywords. If it's not easy, please ignore that and wait for our upgrade. Thanks.
