### ISSUE TITLE
New o wallet is supposed to convert nep5 to ont

### ISSUE THREAD

**Issue by Gettinfukinrich** [ontio/OWallet#67]
So I sent alot of them from Neon to the ledger O wallet that came out today

Gone ... sent but not received ..... No apparent conversion tool at all ... no way to see the nep 5s  ... n Nothing in help

Now what ?

**Comment by MickWang** [comment]
OWallet does not support manage nep-5 tokens with ledger. You can use the chrome plugin-in wallet developed by our community developers. You can find the help in our discord 
channel here.https://discordapp.com/channels/400884201773334540/476579343573975041
Thanks.
