### ISSUE TITLE
Wrong adress

### ISSUE THREAD

**Issue by Denodeno** [ontio/OWallet#75]
Hello, today I tried to import my wallet and came across with a different wallet adress and now I cant access to my actual adress so my coins. My adress, private key, public key, everything is written in a paper, also saved in my dekstop. How can it be? İs there a problem with owallet?

**Comment by MickWang** [comment]
Which version did you use? What is the wallet that you import. is that from ONTO, NEON or OWallet? You can publish your details in our discord channel.https://discordapp.com/channels/400884201773334540/476579343573975041.
Thanks.
